            - name: setup-codeclimate
  # You may pin to the exact commit or the version.
  # uses: remarkablemark/setup-codeclimate@36a0875df5f219a50f616dc9166efadebfe3d56b
  uses: remarkablemark/setup-codeclimate@v2.0.9
  with:
    # Code Climate test reporter version
    codeclimate-version: # optional, default is latest
    # Code Climate test reporter CLI name
    cli-name: # optional, default is cc-test-reporter
          







